### ISSUE TITLE
Java JRE and JDK

### ISSUE THREAD

**Issue by zhudock** [tschf/odl#11]
Sample here, using CURL but the URLs and methodology should be similar 
https://gist.github.com/P7h/9741922

**Comment by tschf** [comment]
I've added in Java 8 JDK and JRE. May need another solution for Java

* It continually get updates, e.g latest is `u121`. 
* The path includes some hashed value such as `e9e7ea248e2c4826b92b3f075a80e441` - not sure if this changes over time.

Maybe querying the DOM at runtime: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html (though, that also has an issue if the download page changes over time)

note. This also applies to some other resources that have that patch version in the downloads, such as ORDS. So either just keep updating this as new patches come out, or reference the master version and fetch the latest. In ords for example, at the moment I've set it up to specify the full version with patch.
