### ISSUE TITLE
InstantClient

### ISSUE THREAD

**Issue by zhudock** [tschf/odl#12]
http://www.oracle.com/technetwork/database/features/instant-client/index-097480.html

There's many add-ons available as well, e.g. JDBC and ODBC support, and SQL*Plus for InstantClient

**Comment by tschf** [comment]
Hmm, hadn't considered this. Open to suggestions here

* basic
* basic lite
* jdbc
* sqlplus
* sdk
* odbc
* wrc

Could make `component` have a value like `instantclient-<subcomponent>`... or a new arg, `subcomponent`

e.g.

```
odl --component instantclient --sub-component odbc --version 12.1.0.2
```
or
```
odl --component instantclient-odbc --version 12.1.0.2
```

I'm perhaps leaning toward the latter here.. :thinking:

**Comment by zhudock** [comment]
I'd go for option 2 as well. looks a little cleaner from the user(s) perspective, but it might complicate the code a bit.

Just to throw another potential issue out, many of those sub-components won't work unless basic or basic-lite already exist. Though I'm not certain it's a reasonable effort to code for that. I'd assume a person searching for a command line utility to download these tools would already be familiar with how to use them

**Comment by tschf** [comment]
> I'd go for option 2 as well. looks a little cleaner from the user(s) perspective, but it might complicate the code a bit.

Wait, which one? I just realised I reversed the order between my sentence and my two examples :D 

```
odl --component instantclient-odbc --version 12.1.0.2
```
right?

**Comment by zhudock** [comment]
yes, that's the one.

**Comment by tschf** [comment]
Verification test:

12.1.0.2.0

| Component | Windows x64 | Windows x86 | Linux x64 | Linux x86 | Linux Other x64 | Linux other x86 | OSX x64 | OSX x86 |
| ---                | ---                   | ---                   | ---             | ---             | ---            | ---            | --- | --- |
| basic          | Y                     | Y                      | Y                | Y               | Y               | Y              | Y | Y |
| basic lite    | Y                     | Y                      | Y                | Y               | Y               | Y              | Y | Y |
| jdbc            | Y                     | Y                      | Y                | Y               | Y               | Y              | Y | Y |
| sqlplus       | Y                     | Y                      | Y                | Y               | Y               | Y              | Y | Y |
| sdk             | Y                     | Y                      | Y                | Y               | Y               | Y              | Y | Y |
| odbc           | Y                     | Y                      | Y                | Y               | Y               | Y              | Y | Y |
| wrc             | Y                     | Y                      | Y                | Y               | Y               | Y              | Y | Y |

11.2.0.4.0

| Component | Windows x64 | Windows x86 | Linux x64 | Linux x86 | Linux Other x64 | Linux other x86 | OSX x64 | OSX x86 |
| ---                | ---                   | ---                   | ---             | ---             | ---            | ---            | --- | --- |
| basic           | Y                     | Y                      | Y                | Y               | Y               | Y              | Y | Y |
| basic lite     | Y                     | Y                      | Y                | Y               | Y               | Y              | Y | Y |
| jdbc            | Y                     | Y                      | Y                | Y               | Y               | Y              | Y | Y |
| sqlplus       | Y                     | Y                      | Y                | Y               | Y               | Y              | Y | Y |
| sdk             | Y                     | Y                      | Y                | Y               | Y               | Y              | Y | Y |
| odbc           | Y                     | Y                      | Y                | Y               | Y               | Y              | NA | NA |
| wrc             | Y                     | Y                      | Y                | Y               | Y               | Y              | Y | Y |

11.1.0.7.0

| Component | Windows x64 | Windows x86 | Linux x64 | Linux x86 | Linux Other x64 | Linux other x86 | OSX x64 | OSX x86 |
| ---                | ---                   | ---                   | ---             | ---             | ---            | ---            | --- | --- |
| basic           | Y                     | Y                      | Y                | Y               | Y               | Y              | NA | NA |
| basic lite     | Y                     | Y                      | Y                | Y               | Y               | Y              | NA | NA |
| jdbc            | Y                     | Y                      | Y                | Y               | Y               | Y              | NA | NA |
| sqlplus       | Y                     | Y                      | Y                | Y               | Y               | Y              | NA | NA |
| sdk             | Y                     | Y                      | Y                | Y               | Y               | Y              | NA | NA |
| odbc           | Y                     | Y                      | NA                | Y               | NA               | Y              | NA | NA |
| wrc             | Y                     | Y                      | Y                | Y               | Y               | Y              | NA | NA |
