### ISSUE TITLE
SQLcl

### ISSUE THREAD

**Issue by tschf** [tschf/odl#2]

**Comment by zhudock** [comment]
https://edelivery.oracle.com/akam/otn/java/sqldeveloper/sqlcl-4.2.0.16.355.0402-no-jre.zip

**Comment by tschf** [comment]
Looks like SQL Dev and SQLcl include the full build in the filename (I guess there could be more packages that do this too). May need to think of a solution to address grabbing the latest build dynamically. 

May consider combining sqlcl and sqldev in the same package, since they are somewhat related.
