### ISSUE TITLE
ORDS

### ISSUE THREAD

**Issue by tschf** [tschf/odl#4]

**Comment by zhudock** [comment]
https://edelivery.oracle.com/akam/otn/java/ords/ords.3.0.9.348.07.16.zip

**Comment by tschf** [comment]
Add 3.0 through 3.0.9. 
It goes back to 2.0.10 - Not sure if worth to go back through full history - http://www.oracle.com/technetwork/developer-tools/rest-data-services/downloads/ords-downloads-2010-2528184.html

**Comment by zhudock** [comment]
Agreed. I'm not sure how far back it's worth going for many of these tools. Is there any benefit to offering the older versions?

**Comment by tschf** [comment]
Only if someone wanted to target a particular release; but I guess at a certain point no one will realistically want to pull a particular version.
