### ISSUE TITLE
SQL Developer

### ISSUE THREAD

**Issue by tschf** [tschf/odl#5]

**Comment by zhudock** [comment]
It's a little odd that the x64 version bundles it's own JDK, the x86 does not

https://edelivery.oracle.com/akam/otn/java/sqldeveloper/sqldeveloper-4.1.5.21.78-x64.zip
https://edelivery.oracle.com/akam/otn/java/sqldeveloper/sqldeveloper-4.1.5.21.78-no-jre.zip
https://edelivery.oracle.com/akam/otn/java/sqldeveloper/sqldeveloper-4.1.5.21.78-macosx.app.zip
