### ISSUE TITLE
Consider architecture terminology

### ISSUE THREAD

**Issue by tschf** [tschf/odl#8]
64:

* x64
* amd64
* x86_64
* 64

32

* 32
* x86
* 386
* i386

Perhaps change argument name to `arch`.

**Comment by zhudock** [comment]
It seems Oracle doesn't really use much consistency in these naming conventions. From a spot check of a few different applications I saw all that you listed above as well as i486, i586 and i686 for 32-bit applications

I'd propose x64 and x86, and changing the argument to arch.

**Comment by tschf** [comment]
Thanks, yeah that sounds good. I liked the amd64 terminology for 64-bit, but for consistency I think x64 and x86 is a good idea.
